# Generated by Django 5.0.dev20230120115851 on 2023-06-21 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiofile',
            old_name='audio_file',
            new_name='audio_path',
        ),
    ]
