# Generated by Django 5.0.dev20230120115851 on 2023-06-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_rename_audio_file_audiofile_audio_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='audio_path',
            field=models.FileField(upload_to='audio/'),
        ),
    ]
