# Generated by Django 5.0.dev20230120115851 on 2023-06-27 08:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0005_rename_video_comment_audio_alter_comment_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
